In [35]:
import numpy as np
import pandas as pd

## DDM Data

Data is from a statement truthness judgement task (Stump, Schumacher, Voss, Klauer, 2026)

`stim_type`, `truth`, and `interaction` are regressed on drift rate, threshold, bias, ndt and ndt variabilty

In [36]:
ddm_data = pd.read_csv("data_application_ddm.csv")
ddm_data

,id,stim_type,factual_truth,resp,correct,rt,rt_question,rt_total,condition
0,1,1,1,0,0,1.503635,1.832254,3.335889,2
1,1,1,0,1,0,0.904189,1.684915,2.589105,4
2,1,0,0,1,0,1.011761,1.133872,2.145633,3
3,1,0,0,1,0,1.115876,2.480435,3.596311,3
4,1,0,1,1,1,1.021979,1.545188,2.567167,1
...,...,...,...,...,...,...,...,...,...
8756,81,1,1,0,0,2.767435,1.033448,3.800884,2
8757,81,0,1,1,1,1.689703,2.668148,4.357851,1
8758,81,0,0,1,0,2.197158,2.135354,4.332511,3
8759,81,1,1,1,1,3.366124,2.809084,6.175208,2
8760,81,1,1,1,1,2.105241,2.526508,4.631749,2

In [37]:
counts = ddm_data.groupby("id")["id"].transform("size")
ddm_data = ddm_data[counts >= 100].copy()

In [38]:
max_num_obs = 116
num_subjects = ddm_data["id"].nunique()

In [39]:
ddm_emp_data = np.full((num_subjects, max_num_obs, 5), np.nan)

In [40]:
for i, id, in enumerate(ddm_data.id.unique()):
    person_data = ddm_data.loc[ddm_data.id == id]
    num_obs = len(person_data.rt)
    rt = person_data.rt
    resp = person_data.resp
    stim_type = person_data.stim_type * 1.0 - 0.5 # effect coding
    truth = person_data.factual_truth * 1.0 - 0.5 # effect coding
    interaction = stim_type * truth
    ddm_emp_data[i, :num_obs, :] = np.c_[rt, resp, stim_type, truth, interaction]

In [41]:
np.save("data_application_ddm.npy", ddm_emp_data)

## RDM Data

Data is from a three-alternative Stroop task (Enkavi et al., 2018)

drift(accumulator == word) = base_drift + drift_boost_1

drift(accumulator == color) = base_drift + drift_boost_2

In [42]:
rdm_data = pd.read_csv("data_application_rdm.csv")
rdm_data

        id     rt  color  word  resp  session  congruent
0        1  0.620      0     2     0        0          0
1        1  0.513      0     0     0        0          1
2        1  0.522      1     0     1        0          0
3        1  0.633      1     1     1        0          1
4        1  0.503      0     0     0        0          1
...    ...    ...    ...   ...   ...      ...        ...
28065  149  0.619      1     1     1        1          1
28066  149  1.041      0     2     0        1          0
28067  149  0.613      0     0     0        1          1
28068  149  0.585      0     0     0        1          1
28069  149  1.057      1     1     1        1          1

[28070 rows x 7 columns]

In [43]:
max_num_obs = 192
num_subjects = rdm_data["id"].nunique()

In [44]:
rdm_emp_data = np.full((num_subjects, max_num_obs, 4), np.nan)

In [45]:
for i, id, in enumerate(rdm_data.id.unique()):
    person_data = rdm_data.loc[rdm_data.id == id]
    num_obs = len(person_data.rt)
    rt = person_data.rt
    resp = person_data.resp
    word = person_data.word
    color = person_data.color
    rdm_emp_data[i, :num_obs, :] = np.c_[rt, resp, word, color]

In [46]:
np.save("data_application_rdm.npy", rdm_emp_data)

## CDM Data

Data is from a Gabor patch orientation judgment task (Kvam, 2019)

`speed_condition`, `difficulty` and their interaction is regressed on drift length, threshold, and non-decision time

In [47]:
cdm_data = pd.read_csv("../data/data_application_cdm.csv")
cdm_data

      id  speed_condition  difficulty  resp_deviation       rt
0      1                0           3       -0.269550  1.25950
1      1                0           2        0.164840  0.86939
2      1                0           1       -0.153290  0.80090
3      1                0           2        0.079275  1.00190
4      1                0           1        0.003619  2.36400
...   ..              ...         ...             ...      ...
5797  12                1           1        0.324980  0.67718
5798  12                1           3        1.197800  0.64035
5799  12                1           3       -0.371310  0.68574
5800  12                1           1       -0.022781  0.64622
5801  12                1           2       -0.135840  0.80213

[5802 rows x 5 columns]

In [48]:
max_num_obs = 599
num_subjects = cdm_data["id"].nunique()

In [49]:
cdm_emp_data = np.full((num_subjects, max_num_obs, 5), np.nan)

In [50]:
for i, id, in enumerate(cdm_data.id.unique()):
    person_data = cdm_data.loc[cdm_data.id == id]
    num_obs = len(person_data.rt)
    rt = person_data.rt
    resp = person_data.resp_deviation
    speed_condition = person_data.speed_condition * 1.0 - 0.5 # effect coding
    difficulty = person_data.difficulty
    interaction = difficulty * speed_condition # needs fixing if difficulty not continuous
    cdm_emp_data[i, :num_obs, :] = np.c_[rt, resp, speed_condition, difficulty, interaction]

In [51]:
np.save("data_application_cdm.npy", cdm_emp_data)